# Docker Compose for LogService
# http://localhost:8700
# Using RabbitMQ broker in 01.docker-compose-RabbitMQ.yml

version: '3.1'
 
services:

  java-logs-service:
    image: tdchien1982/spring:log-services-rabbitmq-2.0
    restart: always
    environment:
      APP_PORT: 9000
      #RABBITMQ_SERVER: localhost
      #RABBITMQ_USER: admin
      #RABBITMQ_PWD: admin
      RABBITMQ_PORT: 56720
      #RABBITMQ_VIRTUAL_HOST: /
    ports:
      - "9100:9000"
    networks:
      - common-network
networks:
    common-network:
      external: true
