# Use postgres/example user/password credentials
version: '3.1'

services:

  jpa-posgres:    
    image: postgres:9.5.25-alpine
    restart: always
    ports:
      - 6432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./postres_database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql
    networks:
      - common-network

networks:
    common-network:
      external: true

# The PostgreSQL database
# Server : postgres_db
# User/Pass : root/root
# Database : root
