
services:
  user-service:
    build: .
    ports: ["8086:8080"]
    container_name: tempo-server-user-service
    labels:
      name: tempo-server

    environment:
      OTEL_SERVICE_NAME: user-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo-server-otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_TRACES_EXPORTER: none # Ignore trace to Tempo
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=local,service.namespace=tdc-demo,service.version=1.0.0
      OTEL_TRACES_SAMPLER: parentbased_traceidratio
      OTEL_TRACES_SAMPLER_ARG: "1.0"
      ORDER_SERVICE_ADDRESS: "http://order-service:8080"

    networks:
      - common-network

networks:
  common-network:
    external: true
