server.port = 8100

# PostgreSQL DB Connection
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.url=jdbc:postgresql://tdc-contabo.tt:5432/admin?createDatabaseIfNotExist=true

# Show all generated SQL inside Hibernate, in beautiful mode, except for LIMIT parameters
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Auto init SQL for PostgreSQL DB, using file data.sql
spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.mode=always

# Default schema for this project:
spring.jpa.properties.hibernate.default_schema: 06.JPA+OptimisticLock

# Turn on L2 cache
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory

# Generate statistic
spring.jpa.properties.hibernate.generate_statistics=true
