spring:
  application:
    name: order-service
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: [ health, info ]

## Call to PaymentService
payment:
  service:
    url: ${PAYMENT_SERVICE_ADDRESS:http://localhost:8088}


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [traceId=%X{trace_id}, spanId=%X{span_id}] [%thread] %logger{36} - TDC - OrderService - %msg%n"