spring.application.name=demo

server.port=${APP_PORT:9090}

spring.mail.host=${EMAIL_HOST:localhost}
spring.mail.port=${EMAIL_PORT:25}
spring.mail.username=${EMAIL_USER:}
spring.mail.password=${EMAIL_PWD:}
spring.mail.properties.mail.smtp.auth=${EMAIL_AUTH_ENABLE:false}
spring.mail.properties.mail.smtp.starttls.enable=${EMAIL_TLS_ENABLE:false}