spring:
  application:
    name: spring-kafka-demo
  kafka:
    bootstrap-servers: kafka.tdc.vv:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    consumer:
      group-id: spring-kafka-demo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false

app:
  kafka:
    topic: test-topic
    partitions: 3
    replicas: 1
    message-count: 100
